// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace ProductivityTrackerService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ProductivityServiceDbContext))]
    partial class ProductivityServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductivityTrackerService.Data.DayEntryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("ProjectWork")
                        .HasColumnType("time");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("ScreenTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("WakeUpTime")
                        .HasColumnType("time");

                    b.Property<string>("WeekDay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WentToGym")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("DayEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
